name: Test

on:
  push:
    branches:
    - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt, llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - uses: giraffate/clippy-action@v1
      - uses: mbrobbel/rustfmt-check@0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: ${{ github.event_name == 'pull_request' && 'review' || 'commit' }}
      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
        with:
          coverageCommand: |
            cargo llvm-cov nextest --lcov --output-path lcov.info
          coverageLocations: |
            lcov.info:lcov
          debug: true
